export default function (req, res) {
  let nodemailer = require('nodemailer')
  const transporter = nodemailer.createTransport({
    port: 465,
    host: "appsters.io",
    auth: {
      user: 'info@appsters.io',
      pass: 'N;v-Om+OIZJ8?tdD',
    },
    secure: true,
  })
  let newDate = new Date()
  const mailData = {
    from: '"Appsters" <info@appsters.io>',
    to: 'info@appsters.io',
    subject: `New Lead Generated By Appsters`,
    html: `<h3>New Lead Generated Client Data Is Listed Below </h3> <p>Name : ${req.body.first}</p> <p> email : ${req.body.email}</p> <p> Date : ${newDate}</p> `
  }
  transporter.sendMail(mailData, function (err, info) {
    if (err)
      console.log(err)
    else
      console.log(info)
  })
  res.status(200)
}
