import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req) {
    try {
        const body = await req.json();
        const { name, email, phone, service, budget, customAmount, message } = body;

        const transporter = nodemailer.createTransport({
            host: "appsters.io",
            port: 465,
            secure: true,
            auth: {
                user: 'support@appsters.io',
                pass: "N;v-Om+OIZJ8?tdD"
            },
            tls: {
                rejectUnauthorized: false
            },
            connectionTimeout: 10000 // 10 seconds timeout
        });

        const mailOptions = {
            from: '"Appsters" <support@appsters.io>',
            to: 'aleehaiderbalti@gmail.com',
            subject: `New Lead Generated By Appsters (Custom App LP)`,
            html: `<table>
                    <tr>
                        <th>Name</th>
                        <td>${name}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>${email}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>${phone}</td>
                    </tr>
                    <tr>
                        <th>Service Type</th>
                        <td>${service}</td>
                    </tr>
                    <tr>
                        <th>Budget</th>
                        <td>${budget}</td>
                    </tr>
                    ${customAmount ? `
                    <tr>
                        <th>Custom Amount</th>
                        <td>$${customAmount}</td>
                    </tr>
                    ` : ''}
                    <tr>
                        <th>Message</th>
                        <td>${message}</td>
                    </tr>
                </table>`
        };

        await transporter.sendMail(mailOptions);

        return NextResponse.json({ message: "Email sent successfully" }, { status: 200 });

    } catch (error) {
        console.error("Error sending email:", error);
        return NextResponse.json({ error: "Error sending email" }, { status: 500 });
    }
}
