import { NextResponse } from "next/server";

const nodemailer = require("nodemailer");

export async function POST(req, res) {
    try {
        const { email, IP, currentdate, pageUrl } = await req.json();
        const brandname = 'Appsters'
        const transporter = nodemailer.createTransport({
            host: "appsters.io",
            port: 465,
            secure: true,
            auth: {
                user: 'support@appsters.io',
                pass: "N;v-Om+OIZJ8?tdD"
            }
        })

        const mailOptions = {
            from: '"Appsters" <support@appsters.io>',
            to: ['zain@iceanimations.com', 'ppc@iceanimations.com', 'hassan.ali@iceanimations.com', 'ali.haider@canvasdigital.org'],
            subject: `New Lead Generated By Appsters`,
            html: `<table>
                    <tr>
                        <th>Email</th>
                        <td>${email}</td>
                    </tr>
                    
                    <tr>
                        <th>Currentdate</th>
                        <td>${currentdate}</td>
                    </tr>
                    <tr>
                        <th>pageUrl</th>
                        <td>${pageUrl}</td>
                    </tr>
                    <tr>
                        <th>Brand Name</th>
                        <td>${brandname}</td>
                    </tr>
            </table>`
        }

        await transporter.sendMail(mailOptions);

        return NextResponse.json({ "message": "Email send sucessfully", "data": [email, brandname, IP, currentdate, pageUrl], "status": 200 });
    } catch (error) {
        return NextResponse.json({ "message": "Failed to send Email", "data": error, "status": 500 });
    }
}

